name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  upload-release:

    runs-on: ubuntu-latest
    needs: [build-macos, build-linux, build-windows, build-modules]

    steps:
    - uses: actions/checkout@v1
    - name: create release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false   
    - name: download artifacts
      uses: actions/download-artifact@v1
      with:
        name: artifacts
    - name: upload macos
      id: upload-macos 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/valradar-macos
        asset_name: valradar-macos
        asset_content_type: application/octet-stream
    - name: upload linux
      id: upload-linux
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/valradar-linux
        asset_name: valradar-linux
        asset_content_type: application/octet-stream   
    - name: upload windows
      id: upload-windows
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/valradar-windows.exe
        asset_name: valradar-windows.exe
        asset_content_type: application/octet-stream
    - name: upload modules
      id: upload-modules
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/modules.zip
        asset_name: modules.zip
        asset_content_type: application/zip


  build-modules:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Zip modules
        run: |
          zip -r modules.zip modules
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifacts/modules.zip
          path: modules.zip
  
  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: |
        cargo build --release
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifacts/valradar-macos
        path: target/release/valradar

  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: |
        cargo build --release
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifacts/valradar-linux
        path: target/release/valradar

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: |
        cargo build --release
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifacts/valradar-windows.exe
        path: target/release/valradar.exe
