name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  upload-release:

    runs-on: ubuntu-latest
    needs: [build-macos, build-linux, build-windows, build-modules]

    steps:
    - uses: actions/checkout@v1
    - name: create release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false   
    - name: download artifacts
      uses: actions/download-artifact@v4
      with:
        path: .
    - name: upload macos
      id: upload-macos 
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        files: |
          valradar-macos
          valradar-linux
          valradar-windows.exe
          modules.zip


  build-modules:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Zip modules
        run: |
          zip -r modules.zip modules
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: modules.zip
          path: modules.zip
  
  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: |
        PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1 cargo build --release
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: valradar-macos
        path: target/release/valradar

  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: |
        cargo build --release
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: valradar-linux
        path: target/release/valradar

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: |
        cargo build --release
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: valradar-windows.exe
        path: target/release/valradar.exe
